### ISSUE TITLE
Alignment preserve cursor position

### ISSUE THREAD

**Issue by peteyy** [junegunn/vim-easy-align#101]
I've tried both ways but I couldn't get them to work. I'd like to preserve the cursor position when I save the file, and call easy align.

`au BufWritePre *.tf ":normal magai{='a"`

or

```vim
function! s:terraform_align ()
  let save_cursor = getpos('.')
  normal gai{=
  call setpos('.', save_cursor)
endfunction
```

**Comment by junegunn** [comment]
How about using a mark? `normal mzgai{ `z`

**Comment by peteyy** [comment]
That's what I was trying to do but with the a register, would that make a difference?

**Comment by junegunn** [comment]
Your autocmd has syntactic errors. Try this:

```vim
au BufWritePre *.tf normal magai{=`a
```

I would use backtick as it restores the column position.

**Comment by peteyy** [comment]
thanks a lot it works now as I've originally expected
