### ISSUE TITLE
Align to *backslash* ( \ ) at bash file

### ISSUE THREAD

**Issue by wow2006** [junegunn/vim-easy-align#103]
Hello, I hope problem to align using *backslash*
This is example:
```sh
cmake \
-G Ninja \
-D USE_EXTERNAL_ZLIB=ON \
..
```

I want it to be like 
```sh
cmake                                          \
-G Ninja                                       \
-D USE_EXTERNAL_ZLIB=ON                        \
..
```

Is it legal to do that?!
Thanks

**Comment by junegunn** [comment]
How about just doing "minus space" alignment (around the last whitespace)?

https://github.com/junegunn/vim-easy-align#examples-using-predefined-rules

**Comment by junegunn** [comment]
You can specify the size of margin around the delimiter, but if you are trying to put the backslashes on a fixed column, like 80, easy-align does not support it. You'll have to post-process the lines after aligning them.

**Comment by wow2006** [comment]
I am really sorry I don't know that

**Comment by junegunn** [comment]
No problem.
