### ISSUE TITLE
Alignment doesn't work on hyphens in C++ comments

### ISSUE THREAD

**Issue by kshenoy** [junegunn/vim-easy-align#107]
Steps to reproduce:

1. Open vim
2. `set ft=cpp`
3. Paste the following:

> // Lorem- ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
> // tempor- invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
> // vero eos- et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
> // no sea- takimata sanctus est Lorem ipsum dolor sit amet.

4. Run `gaip<C-X>-<CR>`

It doesn't align.

However, if I do the same thing after deleting the comment symbols, it aligns on the hyphen

**Comment by junegunn** [comment]
https://github.com/junegunn/vim-easy-align#ignoring-delimiters-in-comments-or-strings

**Comment by kshenoy** [comment]
This worked: `gaip<C-G><C-X>-<CR>`

Thank you for the extensive documentation :)
