### ISSUE TITLE
How to align // style comments

### ISSUE THREAD

**Issue by neybar** [junegunn/vim-easy-align#114]
I have code like this:

```
var foo = "1"; // foo variable
var foofoo = "22"; // foofoo variable
```

I'm having a hard time getting the comments to actually align.  I've tried variations on the following sequence: ```gavip; ctrl-x; /```  For the actual regex, I've tried ```/```, ```\/```, and so on.

**Comment by rod-stuchi** [comment]
Have you tried by command-line:
 
    :EasyAling/\/\//

**Comment by junegunn** [comment]
`-<space>` (around the last whitespaces) is the easiest way to achieve this, since whitespaces in comment (after `//`) are ignored by default.
