### ISSUE TITLE
Aligning only works on full lines

### ISSUE THREAD

**Issue by erez-rabih** [junegunn/vim-easy-align#115]
Hi,

It seems that I can only inline full lines and not only the selected block. Example text:
```clojure
(let [x 1
      xx 2
      xxx 3
      xxxx 4])
```
When the cursor is on the first x I type `gai]<space>`
Result:
```clojure
(let       [x 1
      xx   2
      xxx  3
      xxxx 4])
```
Expected result:
```clojure
(let [x    1
      xx   2
      xxx  3
      xxxx 4])

```

**Comment by junegunn** [comment]
See https://github.com/junegunn/vim-easy-align#using-blockwise-visual-mode

These are the maps I use for clojure development:

```vim
nnoremap <buffer> <leader>a[ vi[<c-v>$:EasyAlign\ g/^\S/<cr>gv=
nnoremap <buffer> <leader>a{ vi{<c-v>$:EasyAlign\ g/^\S/<cr>gv=
```
