### ISSUE TITLE
Is it possible to use words as delimiters.

### ISSUE THREAD

**Issue by DasOhmoff** [junegunn/vim-easy-align#117]
Hi fellow vim users,

First of all I want to say that I really love this plugin and I use it very often.
That being said, now to my question.

Is it possible to use strings or words as delimiters?
For example format those paragraphs:

> one two three four _sample_ five six seven eight
this is _sample_ just another line of text

> void short _()_;
void a_very_long_function_name _()_;

Maybe with some shortcut like `gaap'sample'` or `gaap'('` to those paragraph: 

> one two three four _sample_ five six seven eight
this is &emsp; &emsp; &emsp; &emsp; &nbsp; _sample_ just another line of text

> void short &emsp;  &emsp; &emsp;  &emsp; &emsp; &emsp; &emsp; &nbsp;  &nbsp;  &nbsp;  _()_;
void a_very_long_function_name _()_;

Thank you very much.

**Comment by rod-stuchi** [comment]
Try

    :EasyAlign/ sample/

**Comment by junegunn** [comment]
- Using command: `:EasyAlign/REGEX/`
- Or in intereacive mode: https://github.com/junegunn/vim-easy-align#using-regular-expression
