### ISSUE TITLE
how to make the line after line continuation align

### ISSUE THREAD

**Issue by zhuzhzh** [junegunn/vim-easy-align#119]
```makefile
DPILIB_EMU = libdpi_emu.so
GUI=

SIM_MACRO =  
SIM_OPTS = -c +incdir+../src/v \
           -I$(XEHOME)/share/uxe/etc/ixcom \
           $(SIM_MACRO) \
           +access+rwc \
           +vtimescale+1ns/1ns

VLAN_MACRO =  
```

although = will be alinged, the lines
           -I$(XEHOME)/share/uxe/etc/ixcom \
           $(SIM_MACRO) \
           +access+rwc \
           +vtimescale+1ns/1ns
doesn't align with `-c +incdir+../src/v \`

**Comment by junegunn** [comment]
It's not supported.
