### ISSUE TITLE
can not align when suffix of filename is ".c"

### ISSUE THREAD

**Issue by lifang2012** [junegunn/vim-easy-align#124]
hello, i have following lines:

```
printf("a=aa");
printf("aaa=");
```

 i want to align with "=", when suffix of filename is ".txt", or  without suffix, i tryed to align with command **vipga *=**, got what i expected. but when suffix of filename is ".c",  with command   **vipga *=**,  it does not work, if i delete the first quotation mark in lines, with following:

```
printf(a=aa");
printf(aaa=");
```

then,  i try to align with command **vipga *=**,  align ok.
i tried in vim 8.1.374 and nvim v0.3.0, the result is same.
 any idea? thanks.

**Comment by junegunn** [comment]
See https://github.com/junegunn/vim-easy-align/blob/master/README.md#ignoring-delimiters-in-comments-or-strings
