### ISSUE TITLE
multiple delimiters in one step

### ISSUE THREAD

**Issue by ccshao** [junegunn/vim-easy-align#127]
First thanks for the awesome tool!

Let's say I want to align by two delimiters, by "<-" and ",".  I defined rule for "<-", with the character "<".

```
all_amb<- rbind(wt_amb, ko_amb)
all_sp <- rbind(wt_sp,ko_sp)
all_unsp<- rbind(wt_unsp, ko_unsp)
```

the desired format is 

```
all_amb   <- rbind(wt_amb,  ko_amb)
all_sp    <- rbind(wt_sp,   ko_sp)
all_unsp  <- rbind(wt_unsp, ko_unsp)
```

Currently I have to run comnands twice, first for "<-", and then ",". How could I perform the alignment in one run?

**Comment by arsham** [comment]
You can either make a visual selection and do:

```
:'<,'>EasyAlign */<-\|,/
```
Or after initiating the motion, hit `*` then hit `<C-x>` and enter this regular expression: `<-\|,`.

**Comment by ccshao** [comment]
Thanks for the update, the 2nd approach is usually I used.
