### ISSUE TITLE
Flex box Space-between like alignment

### ISSUE THREAD

**Issue by ultrox** [junegunn/vim-easy-align#131]
I'm writing documentation for a plugin and trying to do the following:

```
Title                                                 some-long-tag
```
I want `some-long-tag` to be aligned to the textwidth value.

It seems I can't do that. I tried to align it with regexp to the $, but whatever I'm doing it's not working.

Currently, I'm doing it with guessing how much space to append before, which is a lot of leg work. I looked at the documentation and it seems you must have the same issue since your tags are super nicely aligned.

**Comment by junegunn** [comment]
It's not supported.

> since your tags are super nicely aligned.

I use a (non-open source) program that converts markdown files to Vim help files, so that's why.
