### ISSUE TITLE
left_align from line start

### ISSUE THREAD

**Issue by ein-shved** [junegunn/vim-easy-align#135]
Hi, is there any option to make pattern, which aligns delimiter to specific position starting from line beginning. The left_align option as I understand counts from the shortest line ending.

I want to use EasyAlign to configure hot-key to auto-fill backslashes inf C-macro definitions to look like next:

    #define foo(f) do {                                                           \
        int __rc = call_foo(f);                                                   \
        process_foo(__rc, f);                                                     \
    } while(0)

e.g. put ```\``` to the 79th position on each line according to coding style.

**Comment by junegunn** [comment]
No, there's no such option.
