### ISSUE TITLE
Animated table examples go too fast to follow - and can't be stopped and restarted . . 

### ISSUE THREAD

**Issue by philiprhoades** [junegunn/vim-easy-align#140]
I have a table with '|' delimiters and three columns - I want to:

right-justify columns one and two (numbers)

and

leave column three left justified . . (text)

Help please?

Thanks

**Comment by junegunn** [comment]
https://github.com/junegunn/vim-easy-align#alignments-over-multiple-occurrences-of-delimiters

Something like this:

```vim
EasyAlign | arrrl
```

**Comment by philiprhoades** [comment]
Thanks for the fast response!
