### ISSUE TITLE
Binding an operation 

### ISSUE THREAD

**Issue by indeedwatson** [junegunn/vim-easy-align#146]
I'd like to do this:

`nmap <leader>t gaip*|`

but when I execute it, the command line displays `:EasyAlign (*_)_` and waits for my input. I've tried adding `<CR>` in multiple places but with no luck.

**Comment by junegunn** [comment]
```vim
nmap <leader>t gaip*<bar>
```

See `:help map_bar`

**Comment by indeedwatson** [comment]
thanks!
