### ISSUE TITLE
Align Fails in python triple quotes

### ISSUE THREAD

**Issue by rickalex21** [junegunn/vim-easy-align#149]
I use triple quotes for documentation in python projects but align ```gaip=``` does not work inside of them. 

*test.py*
```python
"""
Don't work

foo = 'short var'
long_var_name = 'This is a long var'

"""
#works outside
foo           = 'short var'
long_var_name = 'This is a long var'
```

Also, how to I align on tabs/whitespace? I have tried ```gaip *\t``` and```Regular expression:\t```. I could just hit tab 3 times to align this.

```text
Algin me:	Two tabs were inserted before this sentence.
	One tab was inserted here.
	Another sentence here.
```
*Expected result*
```text
Algin me: 	 Two tabs were inserted before this sentence.
		 One tab was inserted here.
		 Another sentence here.
```

Thanks for all the awesome projects.

**Comment by junegunn** [comment]
https://github.com/junegunn/vim-easy-align#ignoring-delimiters-in-comments-or-strings
