### ISSUE TITLE
(Not an issue) Can you transpile to LUA?

### ISSUE THREAD

**Issue by vurtune** [junegunn/vim-easy-align#152]
Hi, this is an awesome plugin.
Can you transpile to LUA, please.

**Comment by junegunn** [comment]
Not interested.

**Comment by hopezh** [comment]
> Hi, this is an awesome plugin. Can you transpile to LUA, please

install it using packer: 
`use 'junegunn/vim-easy-align'

specify the following keymappings for both the normal and insert modes: 
`vim.keymap.set("n", "ga", ":EasyAlign")`
`vim.keymap.set("x", "ga", ":EasyAlign")`

...at least this works on my lua-based neovim setting.
