### ISSUE TITLE
Work with syntax conceal

### ISSUE THREAD

**Issue by sisrfeng** [junegunn/vim-easy-align#153]
After align:
![image](https://user-images.githubusercontent.com/53520949/170714128-78260ca8-3e4d-4f7e-9a57-cae3002f98a0.png)

But does not work well with conceal
![image](https://user-images.githubusercontent.com/53520949/170714197-4b0b112f-f39f-488d-803f-01841bb172ec.png)

**Comment by sisrfeng** [comment]
How to make this plugin work well with syntax conceal ? 
It seems that only configuring this global variable can not achieve this:
![image](https://user-images.githubusercontent.com/53520949/190999659-cf8c14d0-efc9-4287-be64-6255b2acd3d4.png)

Thx!

**Comment by junegunn** [comment]
This plugin wasn't designed/implemented to work with conceal.
