### ISSUE TITLE
Fewer keystrokes to align on =

### ISSUE THREAD

**Issue by nisaacson** [junegunn/vim-easy-align#29]
I often need to align around the = sign within a paragraph. I created a function to do this operation and mapped it to a `leader` key.

Perhaps this is useful for others

https://gist.github.com/nisaacson/4e17cb6abc4345833416

**Comment by MeanEYE** [comment]
@junegunn you can simplify this a bit more by removing creating marks:

```vim
nmap <Leader>= <Plug>(EasyAlign)ip=``
```
