### ISSUE TITLE
Align N-th delimiter as custom delimiter

### ISSUE THREAD

**Issue by hjkatz** [junegunn/vim-easy-align#54]
Is there a way to align using the N-th parameter such as:

-) or 2=

Inside of the easy_align_delimiters variable? What I'm looking to do is:

```
let g:easy_align_delimiters = 
{
    'pattern' : ')',
    'left_margin' : 1,
    'right_margin' : 0,
    'stick_to_left' : 0,
    'n-th_param' : '-'
}
```

Or something similar...

**Comment by junegunn** [comment]
Sorry, but there's no such option. At the moment, I'm not interested in adding more to the plugin.
