### ISSUE TITLE
Adding R sytle assignment to the default list

### ISSUE THREAD

**Issue by hcraT** [junegunn/vim-easy-align#56]
Hi,
first of all thanks for this cool plugin!

I wonder whether you could add the R style assignment that is <code><-</code> to the default list.

Thanks!

**Comment by junegunn** [comment]
Hi, should it be the default alignment rul? I don't think there's a huge demand for that delimiter. And you can easily set up your own rules in your vimrc, for example:

```vim
let g:easy_align_delimiters = { 'R': { 'pattern': '<-' } }
```

**Comment by hcraT** [comment]
Hi,
ok. I knew about the possibility to add it to the config file but I thought it could have been useful to others but you are probably right.

Thanks again for this good plugin and for your time!
