### ISSUE TITLE
Support the custom character

### ISSUE THREAD

**Issue by hanhaoxian** [junegunn/vim-easy-align#57]
Would you like to support aligning by the custom character??
such as fllowing:
a = 2,    %%a is a
bbb = 3,             %%bbb is 3

1.after   align by =
a     = 2,    %%a is a
bbb = 3,             %%bbb is 3

2. after align by %
a     = 2,    %%a is a
bbb = 3,    %%bbb is 3

but it doesn't support %, like that, will you support the custom character like letter or %, ?

**Comment by junegunn** [comment]
There are already a couple of ways to do it. See #26.

**Comment by hanhaoxian** [comment]
thank you, it works fine.
