### ISSUE TITLE
Aligning escaped markdown table

### ISSUE THREAD

**Issue by alcesleo** [junegunn/vim-easy-align#59]
Hey! First I gotta say that this is by far the best aligning plugin I've used, kudos!

I'm wondering if there is any easy way to correctly align a markdown table with escaped pipe symbols in it, for example one field in the table contains this `one \| two`.

Any ideas appreciated!

**Comment by junegunn** [comment]
The default `|`-rule does not take account for backslash-escaped pipe characters. So you need to use a regular expression to do that:

- `*`
- `CTRL-X`
- `\\\@<!|`
    - meaning `|` not preceded (`\@<!`) by a backslash (`\\`)
- Enter

I may even make it the default behavior for `|`. However, a quick search does not lead me to any article that suggests using backslash to escape pipe characters.

- http://stackoverflow.com/questions/17319940/how-to-escape-a-pipe-char-in-a-code-statement-in-a-markdown-table
- https://github.com/gitlabhq/gitlabhq/issues/1238

What do you think about it?

**Comment by alcesleo** [comment]
Shit, you're right. This is actually not valid markdown table-syntax, at least not in Markdown Here which is what I'm using. My bad, thank you for the quick and helpful response!

**Comment by MathieuDR** [comment]
> However, a quick search does not lead me to any article that suggests using backslash to escape pipe characters.


This seems to be fixed in 2017. Perhaps this could be the default behaviour now? Or was something patched for this already?
