### ISSUE TITLE
Easy Align Is Defaulting To Non-Interactive Mode

### ISSUE THREAD

**Issue by gf3** [junegunn/vim-easy-align#60]
Using the latest vim-easy-align and vim 7.4 1-383 with the default mappings it seems that easy align is defaulting to non-interactive mode which doesn't allow one to enter any alignment options. Perhaps I am missing something? I've [included a quick screencast](http://cl.ly/aRyB) to demonstrate the issue.

**Comment by junegunn** [comment]
It looks like you put comment after `<Plug>(EasyAlign)`, it's not allowed. Those characters are interpreted as additional keys for the mapping.

```vim
" NOT THIS
xmap <Enter> <Plug>(EasyAlign) " Start interactive EasyAlign in visual mode

" THIS
" Start interactive EasyAlign in visual mode
xmap <Enter> <Plug>(EasyAlign)
```

**Comment by gf3** [comment]
@junegunn my mistake, thank you so much. it's weird because the VimL syntax highlighting still shows it as a comment.
