### ISSUE TITLE
Unable to set a custom delimiter

### ISSUE THREAD

**Issue by szaghi** [junegunn/vim-easy-align#61]
Dear all,

thank you for this great plugin. 

I need help. I am not able to set an apparently simple custom delimiter (due to my ignorance of vim/easy-align regular expression syntax). 

Let us consider the following snippet:
```fortran
integer:: foo !< this is foo
character(100):: bar !< this is bar
real:: baz !< this is baz
```
The aim is align around `!<` getting:
```fortran
integer:: foo        !< this is foo
character(100):: bar !< this is bar
real:: baz           !< this is baz
```
I have tried with this:
```vim
let g:easy_align_delimiters = {
\ 'c': { 'pattern': '!<' }
\ }
```
but it fails. I have also tried escaping `\!` and `\<` but it does not help. Evidently my pattern is not regular.

A further question is how setup easy align for a more complex alignment of the previous snippet leading to:
```fortran
integer::        foo !< this is foo
character(100):: bar !< this is bar
real::           baz !< this is baz 
```
where the rule should align not only around `!<` but also `::` (whit 0 left margin for this pattern).

Thank you for any suggestions.

My best regards

**Comment by junegunn** [comment]
Looks like a duplicate of #53.

> where the rule should align not only around !< but also :: (whit 0 left margin for this pattern).

In that particular case you can just use the default "space" rule: `*<space>` (around all spaces. Note that spaces in the comment section are ignored)

**Comment by szaghi** [comment]
I am very sorry for the duplication, I have not deeply read the easy align documentation thus I had no idea that comments are by default ignored.

Thank you very much!

**Comment by junegunn** [comment]
No problem :)
