### ISSUE TITLE
Align including first pattern match

### ISSUE THREAD

**Issue by c0ffeeartc** [junegunn/vim-easy-align#62]
Is there an option to include first pattern match into alignment ?
I'm trying to align these c++ function declarations 

    void foo();
    fooConstructor();
    virtual bool fooInit();
    FOO_MACRO(Foo);

to these:

    void.........foo();
    .............fooConstructor();
    virtual bool fooInit();
    .............FOO_MACRO(Foo);

using following pattern:

    let g:easy_align_delimiters = {
    \ 'D': {
    \     'pattern':      '\s\(\S\+\s*(\)\@=',
    \     'left_margin':  0,
    \     'right_margin': 0
    \   }
    \ }

But it omits first match on each line and I get this:

    void.........foo();
    fooConstructor();
    virtual bool fooInit();
    FOO_MACRO(Foo);

**Comment by junegunn** [comment]
If you try `/\s\(\S\+\s*(\)\@=`, you'll notice it doesn't match on 2nd and 4th line. We could add a word boundary symbol to the pattern to make it match (`\(\<\S\+\s*(\)\@=`), but the current implementation of vim-easy-align doesn't work with zero-length delimiters. Sorry, but I think this is just beyond the scope of this plugin :(

**Comment by c0ffeeartc** [comment]
Thanks, will call this function after easy-align for this use case:

```
    function! AlignCppDecalrations()
        silent normal! gv/\S\+\s\+\S\+(^M/\S\+(^M
        let l:curCol = col(".")-1
        let l:i=0
        let l:indent=''
        while(l:i<l:curCol)
            let l:indent.=' '
            let l:i+=1
        endwhile
        execute 'silent normal! gv:s/^\s*\(\S\+(\)/'. (l:indent) .'\1/g^M'
    endfunction
```
