### ISSUE TITLE
Question: why are abbreviations not allowed in interactive mode?

### ISSUE THREAD

**Issue by rstacruz** [junegunn/vim-easy-align#63]
You can use regexps and abbreviated options with `:EasyAlign`:

> `:EasyAlign * | l4r1`

but if you're to use `<Enter>`, you can't use them. The equivalent of this is:

> `vip` `⏎` `<C-l>` `4` `⏎` `<C-r>` `1` `⏎` `*` `|`

which seems more complicated than `*|l4r1`.

**Comment by junegunn** [comment]
Interactive mode is best suited for quick and simple alignments that can be done with just a few keystrokes. The mode finishes immediately when a delimiter is provided (`|`), so `l4r1` in your example will not get a chance to get recognized. And even if we decided to receive more keys after the delimiter, when should we stop? We need an extra key to tell it to stop. (e.g. ` *|l4r1<Enter>`) However, this is not ideal as it requires another keystroke even when we don't need to set any options, which in my case, is most of the time.

Maybe I could add another special key to start an input prompt for abbreviated expressions like `c-l` or `c-r` do, but I think `:EasyAlign` command is more suitable for this case and I've been trying to refrain from adding more features.
