### ISSUE TITLE
easy-align doesn't align on ?=

### ISSUE THREAD

**Issue by cvlmtg** [junegunn/vim-easy-align#65]
?= is a coffeescript operator and currently when aligning to '=' the output is wrong when ?= is used.
I can correct this with g:easy_align_delimiters in my vimrc, but given the fact that I just added a "?" to the default regexp I think it would be nicer to have easy-alig directly support it.
thanks!

**Comment by junegunn** [comment]
Okay, why not :)

**Comment by cvlmtg** [comment]
thanks! :)
