### ISSUE TITLE
Error when pattern contains `\v`

### ISSUE THREAD

**Issue by 19000** [junegunn/vim-easy-align#67]
### What is the right way to use magic mode?
These are the 2 formats of regex I have tried:
- `\v/.../`
- `/\v.../`

And I find **magic mode** and **very magic mode** behave differently. 
Confused.

---------------------
#### Very magic mode
To match a word boundary after `=<Space>`,
I tried `'<,'>EasyAlign /\v(=\s)@<=</`, it echoes: **Invalid regular expression: \v(=\s)@<=<**
Then I use `'<,'>EasyAlign \v/(=\s)@<=</`, it work as expected. (Just placed `\v` outside of `/.../`)

It seems `\v/.../` is the right format, rather than `/\v.../`.

#### Magic mode
But when I test `\m` mode
`'<,'>EasyAlign /\m\(=\s\)\@<=\</` works, 
while `'<,'>EasyAlign \m/\(=\s\)\@<=\</`fail to match.

It seems `/\m.../` is the right format, rather than `\m/.../`.

**Comment by junegunn** [comment]
EasyAlign manually parses the given argument and it does not support any format other than `/.../`. So you're somehow misguided. Anyway, it checks the validity of the pattern by checking if `matchlist('', '\v(=\s)@<=<')` works, and vim does fail to compile the pattern, I'm seeing `E866: (NFA regexp) Misplaced =`.

**Comment by 19000** [comment]
Sorry for `\v(=\s)@<=<`, which is malformed.
The fixed: `\v(\=\s)@<=<`

**Comment by 19000** [comment]
I run `:'<,'>EasyAlign /\v(\=\s)@<=</` while selected the block below

```c  
  bzero(&servaddr, sizeof(servaddr));
  servaddr.sin_family = AF_INET;
  servaddr.sin_addr.s_addr = htonl(INADDR_ANY);
  servaddr.sin_port = htons(SERV_PORT);
```

Error message is:
> Error detected while processing function easy_align#align..\<SNR\>90_align..\<SNR\>90_process..\<SNR\>90_do_align..\<SNR\>90_split_line:
 line   20:
> E54: Unmatched (

**Comment by junegunn** [comment]
So what is the desired output in this case?

Anyway I'll take a look when I get some time. Please note that it is a
known issue that some complex regexes do not work well with easy-align. I
once tried to fix it, but couldn't find the workaround then.

**Comment by junegunn** [comment]
I'm going to fix this issue, but in this particular case, I believe `:EasyAlign=<` will do.

**Comment by 19000** [comment]
It works after update.
The desired result of `:'<,'>EasyAlign /\v(\=\s)@<=</` is pasted below, same as `:EasyAlign=<`
```
  bzero(&servaddr, sizeof(servaddr));
  servaddr.sin_family =      AF_INET;
  servaddr.sin_addr.s_addr = htonl(INADDR_ANY);
  servaddr.sin_port =        htons(SERV_PORT);
```
Just a test for regex support.

Thanks for the quick reply!
