### ISSUE TITLE
Simplify Readme.md

### ISSUE THREAD

**Issue by phcerdan** [junegunn/vim-easy-align#68]
Simplifying the readme.md to get only the basic mapping and  2 or 3 examples will be really handy. The gif is way too long, maybe you can split it in shorter ones.
Or improve the 1 minute guide part to be able to use the plugin after reading it. Right now is a bit confusing.
Just my two cents, the plugin is really cool, thanks :+1:

**Comment by junegunn** [comment]
Thanks for the suggestion. Yeah, I agree that the doc is too long and complicated. Unfortunately I haven't had time to clear things up as these days I'm spending most of my time working on other projects. Splitting GIF into short ones is indeed a good idea, only that it's a very time-consuming and tedious task :(

**Comment by phcerdan** [comment]
I have split them using [http://ezgif.com]()
The quality has been reduced a little bit but they are short enough to watch them in repetition.
[Split Gifs](https://drive.google.com/folderview?id=0B9tL5gD_FpLkcXM0ODBpV3k3ZTQ&usp=sharing)

**Comment by junegunn** [comment]
Ah, thanks. Actually I would have to re-record the GIF since with the current version of easy-align we don't have to be in visual mode thanks to normal mode operator map (e.g. `gaip*=`) and I want to demonstrate how it's done.

**Comment by phcerdan** [comment]
Anyway, I was in my way to create a dumb edit in readme.md. Pull request: #69

**Comment by junegunn** [comment]
Updated the readme with new gifs! Hope you find it more easier to follow. Thanks.
