### ISSUE TITLE
Feature request: Align first N occurences

### ISSUE THREAD

**Issue by paul** [junegunn/vim-easy-align#72]
I occasionally write SQL schema queries, as an example:

```sql
CREATE TABLE accounts (
  id         serial    PRIMARY KEY,

  name       varchar   NOT NULL,
  slug       varchar   NOT NULL UNIQUE,

  settings   jsonb     NOT NULL DEFAULT '{}',

  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  deleted_at timestamp
)
```

This is how I prefer it to look, the with the column name, type and options columns all aligned, but not the options themselves. 

`*<Space>` results in:

```sql
CREATE TABLE accounts (
  id         serial    PRIMARY KEY,

  name       varchar   NOT     NULL,
  slug       varchar   NOT     NULL UNIQUE,

  settings   jsonb     NOT     NULL DEFAULT '{}',

  created_at timestamp NOT     NULL DEFAULT NOW(),
  updated_at timestamp NOT     NULL DEFAULT NOW(),
  deleted_at timestamp
)
```

that is, the `NULL` options get aligned with `KEY`. I can do `<Space>` followed by `2<Space>`, but it would be nice if there was an additional option to do the first n characters, not just the nth.

**Comment by junegunn** [comment]
I considered supporting a range expression, but decided not to do it since it would introduce more ambiguity/complexity in parsing the user input.

Anyway the first-N alignment is possible with `align` option.

1. In interactive mode
    - <kbd>ctrl-a</kbd> <kbd>l</kbd> <kbd>enter</kbd> <kbd>space</kbd>
2. Using command
    - `:EasyAlign\ all` (align left left)

See the following section of the readme page for the details:
https://github.com/junegunn/vim-easy-align#alignments-over-multiple-occurrences-of-delimiters

Closing as wontfix.

**Comment by paul** [comment]
Fair enough. I read the docs, but I guess I didn't realize that was the section
I was looking for. Thanks!

On Sat, Oct 10, 2015 at 8:19 PM, junegunn/vim-easy-align
<reply@reply.github.com>
wrote:
I considered supporting a range expression, but decided not to do it since it
would introduce more ambiguity/complexity in parsing the user input.

Anyway the first-N alignment is possible with align option.

 1. In interactive mode * ctrl-a l enter space
    
    
 2. Using command * :EasyAlign\ all (align left left)
    
    

See the following section of the readme page for the details:

[https://github.com/junegunn/vim-easy-align#alignments-over-multiple-occurrences-of-delimiters] 
https://github.com/junegunn/vim-easy-align#alignments-over-multiple-occurrences-of-delimiters
[https://github.com/junegunn/vim-easy-align#alignments-over-multiple-occurrences-of-delimiters]

Closing as wontfix.

—
Reply to this email directly or view it on GitHub
[https://github.com/junegunn/vim-easy-align/issues/72#issuecomment-147146573] .[https://github.com/notifications/beacon/AAAAuAABT9V9wPB7GqPIiar0r_ykspyQks5o6b6_gaJpZM4GMqXG.gif]
