### ISSUE TITLE
Interactive mode on abort cleanup

### ISSUE THREAD

**Issue by mkoskar** [junegunn/vim-easy-align#74]
After entering interactive mode (e.g., `vip<Return>`) and aborting it with `<Esc>` or `<C-c>` command-line retains EasyAlign's state. There is no reason to keep it there (as oppose to case when EasyAlign wasn't aborted). It is consistent how e.g., search (`/something<Esc>`) behaves.

Also it would be nice if after abort original mode (e.g., visual) is retained (similarly as with search).

**Comment by junegunn** [comment]
Thanks for the suggestion. Updated the code.
