### ISSUE TITLE
Can't align vimrc comments

### ISSUE THREAD

**Issue by kapsh** [junegunn/vim-easy-align#76]
I can not align comments in vim script files which are starting from ". Easy-align doesn't allow ga" with "Unknown delimiter" error.

**Comment by junegunn** [comment]
It looks like many users find the behavior confusing although it is described in the README page.

1. EasyAlign by default ignores delimiters highlighted as string or comment. There are ways to disable that.
2. `ga"` requires a custom alignment rule. See https://github.com/junegunn/vim-easy-align#extending-alignment-rules
3. In this case, you might want to try `ga-<space>` which aligns around the last space that is not highlighted as comment or string

**But**, this very question keeps popping up, I'll just add `"` as one of the default rule.

**Comment by junegunn** [comment]
Please update and see if it works.

**Comment by kapsh** [comment]
Sorry, maybe I missed option g:easy_align_ignore_groups. 
Yes, now rule `"` works, thank you.
