### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by rodfersou** [junegunn/vim-easy-align#77]
At [Examples.md](https://github.com/junegunn/vim-easy-align/blob/master/EXAMPLES.md) shows this rule:
```
let g:easy_align_delimiters['d'] = {
\ 'pattern': ' \ze\S\+\s*[;=]',
\ 'left_margin': 0, 'right_margin': 0
\ }
```
But when I add it into my .vimrc I get this error:
```
Error detected while processing .vimrc:
line  124:
E121: Undefined variable: g:easy_align_delimiters
Press ENTER or type command to continue
```

**Comment by junegunn** [comment]
The code you mentioned adds `d` key to `g:easy_align_delimiters` dictionary that should be defined beforehand. It's pretty basic vimscript so I omitted the part.

**Comment by junegunn** [comment]
I can add the omitted definition part to the examples that update `g:easy_align_delimiters`, but it's already shown in [the first example](https://github.com/junegunn/vim-easy-align/blob/master/EXAMPLES.md#aligning-in-line-comments), so I'll just keep it that way. Thanks for the feedback.

**Comment by rodfersou** [comment]
ok @junegunn thank you for your time
