### ISSUE TITLE
Default when regular expression is empty

### ISSUE THREAD

**Issue by jceb** [junegunn/vim-easy-align#78]
Is there an easy way to reuse the current search pattern for EasyAlign?  I'm thinking of something similar to `:%s//REPLACEMENT` that uses the current search pattern as the given pattern in empty.  I tried `:EasyAlign *//` but this causes each character to be aligned which is not the desired behavior.

As a workaround I'm using `:EasyAlign */<C-r>//` which manually inserts the last pattern.  It feels a bit clunky though.

**Comment by junegunn** [comment]
> reuse the current search pattern

We can make it defaults to the previous search pattern as you suggested if it makes most sense, but I'm not sure about that as I usually never search for the delimiters. (And actually I don't use regular expression at all most of the time.)

> As a workaround I'm using :EasyAlign */<C-r>// which manually inserts the last pattern. 

I think that's a clear and explicit way to achieve what you want.

I noticed some inconsistent (or not well-defined) behavior regarding an empty regular expression.
- In interactive mode, it displays `Invalid regular expression: `
- `:EasyAlign//` goes into the interactive mode as it considers an empty regular expression == no regular expression == no arg
- `:EasyAlign*//` however, sees every character as the delimiter
    - So this feels like a bug, behavior that is not intended.

**Comment by jceb** [comment]
I'd suggest to emulate @:s/@ behavior closely with EasyAlign and regexp search as this is what vim users would expected/associate.  To go even one step further is to set the search pattern as well when a pattern is specified, i.e. @:EasyAlign */test/@ would set the current search pattern to test which is also what @:s/@ does.

**Comment by junegunn** [comment]
I actually do not see the point and I was just going to disallow an empty regex. Since like I said I don't understand why one would search for delimiters for alignment. Most of the time I align text around delimiters like `=`, `|` and `<space>`, and I never search for their occurrence. Can you give me an example of your use case?

**Comment by jceb** [comment]
I'm using patterns quite a lot.  For example I use the pattern `.\*|` to align Asciidoc tables.

The thing with reusing the current search pattern is that it's easy to peek into what will be aligned/replaced without executing the alignment/replacement command yet.  I picked up this technique in one of the vimcasts and find it very useful.

Since I'm not a programmer but I work a lot with arbitrary text files patterns are most valuable to my job.  I hope this is convincing :-)  I can offer to implement this feature some time in May.  What do you think?

**Comment by junegunn** [comment]
Hmm, I'm still not convinced it's a good default for easy-align. I agree that it's pretty useful for `:s`, but I personally never considered using the search pattern as the delimiter while using easy-align. But it's an easy fix, so let's do it and see how it turns out.

**Comment by jceb** [comment]
Thanks, much appreciated!
