### ISSUE TITLE
Align on ":" ?

### ISSUE THREAD

**Issue by metal3d** [junegunn/vim-easy-align#79]
Hi, 
Congrat for you work ! I just have a strange problem... maybe I did it wrong. 

Take this buffer content:

```
a= b
bb= cc
d= gg
vvvvv= gggg

a: b
bb: cc
d: gg
vvvvv: gggg
```

On the first paragraph: gaip =

It's ok
```
a     = b
bb    = cc
d     = gg
vvvvv = gggg
```

On the secon paragraph: gaip :
```
a:     b
bb:    cc
d:     gg
vvvvv: gggg
```

As you can see, the ":" char is not placed as the "=".

It's a bug or am I doing something wrong ?

**Comment by metal3d** [comment]
Ok... I found your example with "vipga->:" I didn't understood what it makes exactly but it works :)

**Comment by junegunn** [comment]
> It's a bug or am I doing something wrong ?

It's the intended behavior. The default rule dictates that colons "stick to left"
See: https://github.com/junegunn/vim-easy-align/blob/master/autoload/easy_align.vim#L33-L46

<kbd> →</kbd> is a key for unsetting the `stick_to_left` setting.

- <kbd>ga</kbd><kbd>ip</kbd><kbd>→</kbd><kbd>:</kbd>
    - <kbd>ga</kbd> Start easy-align
    - <kbd>ip</kbd> for inner-paragraph,
    - <kbd>→</kbd> unset `stick_to_left`
    - <kbd>:</kbd> and align around colons

- <kbd>v</kbd><kbd>ip</kbd><kbd>ga</kbd><kbd> →</kbd><kbd> :</kbd>
    - <kbd>v</kbd> Visually select
    - <kbd>ip</kbd> inner-paragraph,
    - <kbd>ga</kbd> start easy-align,
    - <kbd>→</kbd> unset `stick_to_left`
    - <kbd>:</kbd> and align around colons

**Comment by metal3d** [comment]
Right, and it works as expected. Maybe documentation in README can precise this. Or maybe I didn't read the entire README as I should ;)

But, thanks ! It works and it's a very nice vim plugin !
