### ISSUE TITLE
[feature] Specify column width

### ISSUE THREAD

**Issue by lervag** [junegunn/vim-easy-align#80]
I was wondering if it would be possible to add an option that specifies a fixed (minimum) column width. This would make it possible to align tables but keep the columns equally large, independent of the content of the columns...

**Comment by junegunn** [comment]
Interesting, but I currently have no plan to add more features as I think the plugin is already quite complex. I'll leave the issue open if you don't mind.

**Comment by lervag** [comment]
I agree that the plugin is complex! In fact, this is the first time in a long time that I found anything I missed! I think being able to specify column width is the only thing that is missing.

I don't mind that you keep the issue open, but if you don't really intend to add the feature, then I won't mind if you close the issue either. I can partly solve this manually by filtering my content through `column -c ...`.
