### ISSUE TITLE
Auto align on save file.

### ISSUE THREAD

**Issue by wpoosanguansit** [junegunn/vim-easy-align#81]
Hi,

I am trying out the plugin and I am wondering if there is any configuration to apply the plugin to the file or paragraph just written on every save?  I am just a casual Vim user.  So it would be great if there is one or if it can be shown how that can be accomplished.  Thanks for your help.

**Comment by junegunn** [comment]
You can use `BufWritePre` autocmd for the purpose. For example,

```vim
autocmd! BufWritePre <buffer> silent normal gaip=
```

Though I'm not sure if it's a good idea (you may end up with an undesired result).
