### ISSUE TITLE
Small question about why semicolon isn't in the default rules

### ISSUE THREAD

**Issue by unphased** [junegunn/vim-easy-align#86]
A very common situation I run into for aligning things manually is when I have multiple short oneliners in the code. This is often a no-go for style because it looks messy, but aligning the code improves this dramatically. Take this code as an example: 

```
void debugCB(GLenum source, GLenum type, GLuint id, GLenum severity,
    GLsizei length, const GLchar* message, const void* userParam) {
    std::string sourceS;
    std::string typeS;
    std::string severityS;
    switch (type) {
        case GL_DEBUG_TYPE_ERROR:               typeS = "error"; break;
        case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR: typeS = "deprecated behavior"; break;
        case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR:  typeS = "undefined behavior"; break;
        case GL_DEBUG_TYPE_PORTABILITY:         typeS = "portability"; break;
        case GL_DEBUG_TYPE_PERFORMANCE:         typeS = "performance"; break;
        case GL_DEBUG_TYPE_OTHER:               typeS = "other"; break;
        case GL_DEBUG_TYPE_MARKER:              typeS = "marker"; break;
    }
    switch (source) {
        case GL_DEBUG_SOURCE_API:             sourceS = "API"; break;
        case GL_DEBUG_SOURCE_WINDOW_SYSTEM:   sourceS = "window system"; break;
        case GL_DEBUG_SOURCE_SHADER_COMPILER: sourceS = "shader compiler"; break;
        case GL_DEBUG_SOURCE_THIRD_PARTY:     sourceS = "third party"; break;
        case GL_DEBUG_SOURCE_APPLICATION:     sourceS = "application"; break;
        case GL_DEBUG_SOURCE_OTHER:           sourceS = "other"; break;
    }
    switch (severity) {
        case GL_DEBUG_SEVERITY_HIGH:         severityS = "high"; break;
        case GL_DEBUG_SEVERITY_MEDIUM:       severityS = "medium"; break;
        case GL_DEBUG_SEVERITY_LOW:          severityS = "low"; break;
        case GL_DEBUG_SEVERITY_NOTIFICATION: severityS = "notification"; break;
    }
    std::cerr << "GL Debug " << sourceS << " " << typeS << " " << severityS << " #" << id << ": " << message << std::endl;
}
```

Aside from the last line in the function it is mostly almost going to fit in 80 columns! Aligning at the `:` was simple enough but I'm always finding a reason to align to semicolon for these types of repetitive short oneliners that can be concatenated, and having unaligned multi-oneliners is arguably terrible. I guess what it would help with *here* is let us put all of the `break;`s into one column.

I'm looking at the rules [here](https://github.com/junegunn/vim-easy-align/blob/2.9.6/autoload/easy_align.vim#L) and I dont see it. 

I think the way to deal with this is to make a custom rule to add. But I'm curious why this isn't used more.

This issue also doubles as a feeler for if author would consider merging a PR that adds a semicolon-rule to the defaults.

**Comment by junegunn** [comment]
> But I'm curious why this isn't used more.

I don't know, actually you're the first one to bring this. And this plugin has been around for over three years, so I guess there's not much demand for the case.

> This is often a no-go for style because it looks messy

Maybe that's the reason people don't need this too much? It's certainly not a widely recommended style. So I don't think we need to add it to the default set of rules, especially when it's trivial to define a custom rule for it.

```vim
let g:easy_align_delimiters = {
  \ ';': { 'pattern': ';', 'left_margin': 0, 'stick_to_left': 1 } }
```

And in this particular case where the lines end with a single token, `break;`. I would just align around the last spaces. <kbd>-</kbd><kbd>space</kbd>

I'm going to close the issue, but thanks for the suggestion.
