### ISSUE TITLE
Vary margins by Nth delimiter?

### ISSUE THREAD

**Issue by Celti** [junegunn/vim-easy-align#87]
I'm looking for a way to have the margins for a rule vary by the Nth (specifically, the first) delimiter.

Given a block like this...
```
^ Skill ^ Dif. ^ Rel. ^ Pts. ^ Lev. ^
| Anthropology | H | IQ-1 | [2] | 12 |
| Body Language | A | PE | [2] | 13 |
| Brawling | E | DX+1 | [2] | 13 |
| Carousing | E | HT+1 | [2] | 12 |
```

I want a left_margin of 2 and a right_margin of 2 for everything *except* the first delimiter, which needs a right_margin of 1:
```
^ Skill                                   ^  Dif.  ^  Rel.  ^  Pts.  ^  Lev.  ^
| Anthropology                            |  H     |  IQ-1  |  [2]   |  12    |
| Body Language                           |  A     |  PE    |  [2]   |  13    |
| Brawling                                |  E     |  DX+1  |  [2]   |  13    |
| Carousing                               |  E     |  HT+1  |  [2]   |  12    |
```

Is this possible?

----
Context for the curious, the syntax is that of DokuWiki tables: `^` is for headers, `|` is for normal cells, and a double-space on both sides of the cell centers the content, while a double-space on only one side of the cell aligns the content away from that side. The tables in question are for GURPS 4th Edition character skill lists.

**Comment by Celti** [comment]
Oh duh, I just realised I can make this work with two commands: `:EasyAlign */[|^]/r2l2` followed by `:EasyAlign 1/[|^]/r1`.

So to further my question, is there a way to define a custom alignment rule/delimiter that follows this pattern, or shall I just accept that I need to use two different commands and move on?

**Comment by junegunn** [comment]
Good to hear that you find the solution. Specifying different margins in a single alignment is not supported. I suppose you already know, but you can define your custom command that executes two commands at once.

```vim
command! -range DA exec '<line1>,<line2>EasyAlign */[|^]/r2l2'
                \| exec '<line1>,<line2>EasyAlign 1/[|^]/r1'
```

**Comment by Celti** [comment]
Yep, I knew that one. Thanks for confirming that it's not supported; I might try and add that feature myself, farther down the line — but for now the custom command will work just fine for me.
