### ISSUE TITLE
only aligns one column

### ISSUE THREAD

**Issue by unphased** [junegunn/vim-easy-align#88]
Very commonly you have something that looks like this: 

    a, bbb, cc, d
    abab, babab, b, a
    ajz, za, a, a

after aligning on `,` we get

    a,    bbb, cc, d
    abab, babab, b, a
    ajz,  za, a, a

This is only aligning the first column... 

Furthermore, even if the number of delimiters is not the same across the lines it should make a best-effort attempt to align, e.g. shortening the second line: 

    a, bbb, cc, d
    abab, babab
    ajz, za, a, a

This should become: 

    a,    bbb,  cc, d
    abab, babab
    ajz,  za,   a,  a

**Comment by junegunn** [comment]
This plugin can do that and more. You'll find the answers in the README page.
- `*,` instead of `,`
- `CTRL-U` to unset `ignore_unmatched` property

![](https://raw.githubusercontent.com/junegunn/i/master/easy-align/commas.gif)
