### ISSUE TITLE
rolling back to previous normal align

### ISSUE THREAD

**Issue by zirho** [junegunn/vim-easy-align#91]
Hi, 

How can I roll it back if the buffer when away. When I can not undo alignment.

```
import * as Utils                  from '../utils';
import * as TwitterApi             from '../apis/twitter';
```

It's kinda hard for me to figure out.
Should I do it one by one?

Thanks!

**Comment by junegunn** [comment]
> Should I do it one by one?

Yes, line by line. If you have the following mappings:

```vim
" Start interactive EasyAlign with a Vim movement
nmap ga <Plug>(EasyAlign)
nmap gaa ga_
```

`gaa*<space>` to align only the first line, then you move the cursor to the second line and hit `.` to repeat the same alignment (repeating with `.` require tpope/vim-repeat).

**Comment by zirho** [comment]
Thank you!
