### ISSUE TITLE
Builtin mapping ga vs suggested easy-align mappings

### ISSUE THREAD

**Issue by kiryph** [junegunn/vim-easy-align#92]
I am not entirely happy with the suggested mapping `ga`. I want to use https://github.com/tpope/vim-characterize which also redefines `ga` but adds functionality to the original `ga` (`:h :ascii`).

I know I can define it to my own liking. However, using a default mapping makes sense for me: for instance, remapping all vim builtins would be unwise, you would be unable to use vim somewhere else.

A first suggestion would be: add to the docs a replacement mapping for the builtin print ascii value of character under the cursor: something like `gA`.

However, I am also not convinced that this is a good one and whether this is in the spirit of vim.

Have you ever considered to promote one of the following mappings instead of `ga` in the first place:

- `nmap <bar> <Plug>(EasyAlign)` (overwrites builtin which I don't use)
- `nmap g<bar> <Plug>(EasyAlign)` (free mapping)
- `nmap g= <Plug>(EasyAlign)` (free mapping)
- `nmap gQ <Plug>(EasyAlign)` (overwrites builtin which I don't use)
- `nmap gl <Plug>(EasyAlign)` (lower case L, free mapping) like https://github.com/tommcdo/vim-lion

My favorites would be `gl` and `g=`.

**Comment by junegunn** [comment]
Thanks for the suggestion. Yes, I'm aware that `ga` overrides the default `ga` and that made me hesitate a bit when I decided to promote `ga` at some point. I used to [suggest `<leader>a`](https://github.com/junegunn/vim-easy-align/commit/b8e93f96b83c2f3fdfc7e4e6aff0477faee2cfdd) before `ga`.

Basically I agree to your point, but after all it's just a suggestion, an example configuration based on my own preference. I rarely use the default `ga` and when I have to, I can just use `:ascii` command instead, so not being able to use it has never been an issue to me. And nothing else felt more intuitive and easier to type than `ga`, so I decided to go for it and recommend it. The users who actually use `ga` will probably choose different key sequence. As you might have noticed, this plugin does not define any mappings by default. The decision is completely up to the user.

Related: https://github.com/justinmk/vim-sneak#how-dare-you-remap-s

**Comment by kiryph** [comment]
I certainly understand you:

- `ga` is a super keycombo. There aren't many two letter combos with less finger movement, possibly dd and gg :-). Both letters on the homerow.
- I also think most people do not use the builtin `ga` that much often.

Now I guess, I want to convince tpope to add something like `:Ascii` to commentary and make the `ga` mapping easy to customize. Something like `g?` (who uses rot13 anyway).
