### ISSUE TITLE
syntax highlighting in vim command line

### ISSUE THREAD

**Issue by dkarter** [junegunn/vim-easy-align#94]
This is not really an issue, more of a question.

How do you get vim to syntax highlight the command line? I noticed you have `:EasyAlign ...` highlighted in different colors than the rest of the command in the command line.

Thanks for all your great work on the plugins I use every day!!! 💯

**Comment by junegunn** [comment]
It's not a real command-line. The plugin's just echoing some message in colors of different highlight groups and waiting for a keystroke using `getchar()` call.

```vim
:echohl Error | echon ':foo' | echohl WarningMsg | echon 'bar' | echohl None | call getchar()
```

Hope this answers your question. Thanks.
