### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by shake0** [junegunn/vim-easy-align#95]
Unfortunatelly the MIT License requires some custom variables. So I guess mentioning it in the README isn't enough.
[OSI MIT  License](https://opensource.org/licenses/MIT)

Big fun of this plugin! :)
[MIT Lisence within Arch community](https://wiki.archlinux.org/index.php/Arch_packaging_standards#Licenses)

**Comment by junegunn** [comment]
Hi, the source code contains the full license, so I think it suffices. Thanks.

https://github.com/junegunn/vim-easy-align/blob/master/autoload/easy_align.vim
