### ISSUE TITLE
Problem with filetype=ruby

### ISSUE THREAD

**Issue by rderik** [junegunn/vim-easy-align#97]
The problem seems to be only with filetype=ruby
I have this text:
```
Rails.application.routes.draw do
  get 'book/list'
  get 'book/new'
  post 'book/create'
  patch 'book/update'
  get 'book/list'
  get 'book/show'
  get 'book/edit'
  get 'book/delete'
  get 'book/update'
  get 'book/show_subjects'
end
```
And when I try to run the command:
`:%EasyAlign /'/ {'rm': 0}`

Nothing happens. But if I go:
```
:set ft=text
:%EasyAlign /'/ {'rm': 0}
```
It works as expected.

I'm using the following Plugins that might cause the error:
```vim
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-rails'
```
Thanks in advance for any help.

**Comment by rderik** [comment]
It was not an issue, it was a lack of understanding how the plugin works if you are having a problem like this is probably because you are not ignoring groups. the command would work like this:

`:%EasyAlign /'/ {'ig': [], 'rm': 0}`

**Comment by junegunn** [comment]
I would select the lines inside the do block and align around the first space.

- `ga<space>`

**Comment by rderik** [comment]
That sounds like a better solution.

Thanks and keep up the good job with all of your projects!
